import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Nav } from "../components/nav";
import { Hero } from "../components/hero";
import { Intro } from "../components/intro";
import { Treatments } from "../components/treatments";
import { CatelogueSnippet } from "../components/catelogue/catelogueSnippet";
import { Schemes } from "../components/schemes";
import { TestimonialCard } from "../components/testimonials/testimonialcards";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <div className="smmd:h-[400px] bg-gray-300 relative -z-20">
        <div className="absolute top-0 left-0 object-cover w-full smmd:h-[400px] h-full -z-10">
          <Image
            src="/rosebanner.png"
            alt="Banner Image"
            layout="fill"
            objectFit="cover"
            priority="true"
          />
        </div>

        <div className="py-14 smmd:py-0">
          <div className="smmd:grid smmd:grid-cols-2 flex flex-col gap-4 pr-4 pl-6">
            <div className="flex smmd:justify-end justify-center">
              <div className="flex flex-col justify-center relative">
                <div className="absolute -translate-x-2 -translate-y-2 w-[300px] h-[230px] border-2 border-black"></div>
                <img
                  src="/claire.png"
                  className="w-[300px] h-[230px] object-cover z-10"
                ></img>
              </div>
            </div>
            <div className="flex smmd:justify-start justify-center">
              <div className="flex flex-col smmd:justify-center smmd:h-[400px]">
                <h3 className="text-left text-2xl font-bold z-20">About Me</h3>
                <div className="w-[100px] h-0.5 bg-black z-20"></div>
                <p className="w-[300px] mt-4 text-left z-20">
                  Hello I'm Claire I run JUST Aesthetics, we offer a wide range
                  of treatments and services to our clients, such
                  as non-surgical treatments, results-driven skincare, and
                  nutritional health. Our clinic is located on Station Road in
                  Croston. 
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="grid smmd:grid-cols-2 grid-cols-1 gap-10 smmd:gap-4 max-w-[1200px] mx-auto px-4 smmd:py-20 py-10">
        <div className="flex flex-col gap-2">
          <h3 className="text-2xl font-bold border-l-4 border-black pl-2">
            Why choose Claire <br />
            for your medical <br />
            treatments
          </h3>
        </div>
        <div className="flex flex-col gap-2">
          <p className="text-md">
            At <strong>JUST Aesthetics</strong>, I understand that as we age,
            the appearance of our skin changes and this is something we can’t
            change, but that doesn’t mean you can’t look youthful. My treatments
            can help you achieve just that.{" "}
          </p>
        </div>
      </div>

      <h2 className=" w-full text-center text-2xl font-medium">Testimonials</h2>
      <div className="grid grid-cols-3 mx-24 gap-12 mt-12">
        <TestimonialCard name="Nick" body="asdsafdsguidgjaodifgad" />
        <TestimonialCard name="Nick" body="asdsafdsguidgjaodifgad" />
        <TestimonialCard name="Nick" body="asdsafdsguidgjaodifgad" />
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
