import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Nav } from "../components/nav";
import { TestimonialCard } from "../components/testimonials/testimonialcards";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <div className="smmd:h-[400px] bg-gray-300 relative -z-20">
        <div className="absolute top-0 left-0 object-cover w-full smmd:h-[400px] h-full -z-10">
          <Image
            src="/rosebanner.png"
            alt="Banner Image"
            layout="fill"
            objectFit="cover"
            priority="true"
          />
        </div>

        <div className="py-14 smmd:py-0">
          <div className="smmd:grid smmd:grid-cols-2 flex flex-col gap-4 pr-4 pl-6">
            <div className="flex smmd:justify-end justify-center">
              <div className="flex flex-col justify-center relative">
                <div className="absolute -translate-x-2 -translate-y-2 w-[300px] h-[230px] border-2 border-black"></div>
                <img
                  src="/claire.png"
                  className="w-[300px] h-[230px] object-cover z-10"
                ></img>
              </div>
            </div>
            <div className="flex smmd:justify-start justify-center">
              <div className="flex flex-col smmd:justify-center smmd:h-[400px]">
                <h3 className="text-left text-2xl font-bold z-20">About Me</h3>
                <div className="w-[100px] h-0.5 bg-black z-20"></div>
                <p className="w-[300px] mt-4 text-left z-20">
                  Hello I'm Claire I run JUST Aesthetics, we offer a wide range
                  of treatments and services to our clients, such
                  as non-surgical treatments, results-driven skincare, and
                  nutritional health. Our clinic is located on Station Road in
                  Croston. 
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="grid smmd:grid-cols-2 grid-cols-1 gap-10 smmd:gap-4 max-w-[1200px] mx-auto px-4 smmd:py-20 py-10">
        <div className="flex flex-col gap-2">
          <h3 className="text-2xl font-bold border-l-4 border-black pl-2">
            Why choose Claire <br />
            for your medical <br />
            treatments
          </h3>
        </div>
        <div className="flex flex-col gap-2">
          <p className="text-md">
            At <strong>JUST Aesthetics</strong>, I understand that as we age,
            the appearance of our skin changes and this is something we can’t
            change, but that doesn’t mean you can’t look youthful. My treatments
            can help you achieve just that.{" "}
          </p>
        </div>
      </div>

      <h2 className=" w-full text-center text-2xl font-medium">Testimonials</h2>
      <div className="grid grid-cols-3 mx-24 gap-12 mt-12">
        <TestimonialCard
          name="Lauren Snape"
          body="Had one of the best experiences with JUST Aesthetics everything from service to aftercare was perfect 10. Claire is an absolute master at what she does, and I highly recommend her if you want a safe, clinically, clean and well priced treatment without product compromise."
        />

        <TestimonialCard
          name="Emma Otter"
          body="What a treat to experience, the new treatment at Just Aesthetics - 𝐂𝐫𝐲𝐬𝐭𝐚𝐥 𝐂𝐚𝐫𝐛𝐨𝐱𝐲 𝐂𝐎𝟐 𝐅𝐚𝐜𝐢𝐚𝐥. Claire went through the whole process with me so that I knew what to expect and how my face would feel during the treatment. I opted for a dermaplaning treatment at the same time which complements this facial really well. We are four weeks along now and my face still looks fresh, plumped and healthy. Highly recommend this treatment and Claire."
        />

        <TestimonialCard
          name="Moira Grobicki"
          body="Claire is an excellent aesthetic Nurse, she is so kind and understanding, she goes out of her way to help you, especially if you are needing extra support. I highly recommend seeing Claire, who will always give you the very best care."
        />

        <TestimonialCard
          name="Laura Nolan"
          body="Had my first ever Derma peel today and it was fantastic! Lovely treat which I won in the Just Aesthetic competition. I feel rejuvenated! Claire is very informative about her treatments and talks through everything with you before proceeding. She also puts you at ease during the treatment. The little aftercare package is also a lovely idea. Thanks Claire x"
        />

        <TestimonialCard
          name="Vicki Hock"
          body="Had a Dermapeel with Claire. She made to feel very relaxed, the procedure was clearly explained beforehand so I knew what to expect. She also took time to understand my skin and gave great advice on what to do with my skin going forward. My skin looks and feels much clearer and fresher. Can’t wait to book in for my next one. Thanks Claire x"
        />

        <TestimonialCard
          name="Michael Nolan"
          body="My wife had a derma peel back in February and was really pleased. Since then and after advice from Claire she has now started to use the Cosmed products. I'm sure she'll be returning."
        />

        <TestimonialCard
          name="Amanda Quirk"
          body="I have had my third facial peel this evening and my skin feels and looks amazing! Claire is a very experience qualified nurse which I feel to be of the upmost importance to deliver this treatment. Very professional. I have been guided through step by step of what differing types of peels will be of most benefit for my skin at each stage. I can't recommend Claire highly enough."
        />

        <TestimonialCard
          name="Danielle Smith LUaesthetics"
          body="I would 100% Recommend Claire. I had my lips and cheeks done by Claire wanting a more plumpy look to my lips and a suttle enhancement to my cheeks. Claire was very professional, informative and thorough throughout. Claire took the time to understand the look that I wanted to achieve and made me feel at ease during the treatments. Claire was very knowledgeable about her treatments and ensured that I had full understanding of the treatments, products and any side effects. I love my results and feel so much more confident now! Also after treatments Claire gave me a little goody bag (which I loved) with products in which we’re lovely 😊 Thanks a lot Claire 🥰 I will definitely be returning! Xx"
        />

        <TestimonialCard
          name="Cathryn Blackburn"
          body="Had a Dermapeel with Claire. Was made to feel very relaxed, the procedure was clearly explained beforehand so I knew what to expect. Skin looks much clearer and fresher. Will definitely return! Thanks Claire."
        />
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
