import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Nav } from "../components/nav";
import { Hero } from "../components/hero";
import { Intro } from "../components/intro";
import { Treatments } from "../components/treatments";
import { CatelogueSnippet } from "../components/catelogue/catelogueSnippet";
import { Schemes } from "../components/schemes";

export default function contacts() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <h1 className="w-full text-center my-24 text-3xl ">Contact us</h1>
      <div className="px-4  sm:px-24 ">
        <iframe
          src="https://snazzymaps.com/embed/375923"
          width="100%"
          height="440px"
        ></iframe>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 mt-24 gap-y-8">
        <div className="border-2 border-black mx-8 sm:mx-24 xl:mx-32">
          <h2 className=" w-full text-center py-8 text-3xl">Address</h2>
          <p className="w-full text-center py-8 text-xl">
            62 Station Rd, Croston, Preston PR26 9RN
          </p>
        </div>

        <div className="border-2 border-black mx-8 sm:mx-24 xl:mx-32">
          <h2 className=" w-full text-center py-6 text-3xl">Contact</h2>
          <p className="w-full text-center py-6 text-xl">07919282994</p>
          <p className="w-full text-center py-6 text-xl">
            hello@justaesthetics.co.uk
          </p>
        </div>
      </div>

      <div className="relative w-full bg mt-24 mb-4 h-[700px]">
        <div className="h-full w-full relative">
          <Image
            src="/facebanner.png"
            alt="Banner Image"
            layout="fill"
            objectFit="cover"
          />
        </div>
        <div className="w-full absolute left-0 top-0 z-10  px-6 sm:px-8 md:px-2 xl:px-24 mx-auto grid grid-cols-1 md:grid-cols-2 gap-10">
          <div className="flex flex-col justify-center px-6 sm:px-8  xl:px-24">
            <h2 className="text-3xl pl-4 font-semibold mb-8 mt-12">
              Message Us
            </h2>
            <form
              className="flex flex-col"
              name="PartnershipForm"
              method="POST"
              action="/success"
              netlify-honeypot="bot-field"
              data-netlify="true"
            >
              <input type="hidden" name="form-name" value="paymentsForm" />
              <p className="hidden">
                <label>
                  Don't fill this out if you're human:
                  <input name="bot-field" />
                </label>
              </p>

              <div>
                <input
                  className="border-b-4 bg-transparent border-black text-2xl placeholder-black  appearance-none   mb-2 w-full pl-4 py-4 px-1 my-6"
                  id="fName"
                  type="text"
                  name="Name"
                  placeholder="Name*"
                  required
                ></input>
              </div>

              <div>
                <input
                  className="border-b-4 bg-transparent border-black text-2xl placeholder-black  appearance-none   mb-2 w-full pl-4 py-2 px-1 my-6"
                  id="email"
                  type="text"
                  name="email"
                  placeholder="Email Address *"
                  required
                ></input>
              </div>

              <div>
                <input
                  className="border-b-4 bg-transparent border-black text-2xl placeholder-black  appearance-none   mb-2 w-full pl-4 py-2 px-1 my-6"
                  id="phone"
                  type="text"
                  name="phone"
                  placeholder="Phone Number"
                ></input>
              </div>

              <div>
                <select
                  className="border-b-4 bg-transparent border-black text-2xl placeholder-black  appearance-none   mb-2 w-full pl-4 py-2 px-1 my-6"
                  id="phone"
                  type="text"
                  name="phone"
                  placeholder=""
                  required
                >
                  <option value="1">Enquiry Type*</option>
                  <option value="2">Bookings</option>
                  <option value="3">Treatments</option>
                  <option value="4">Services</option>
                </select>
              </div>

              <div className="col-span-2">
                <textarea
                  className="border-b-4 bg-transparent border-black text-2xl placeholder-black  appearance-none   mb-2 w-full pl-4 py-2 px-1 my-6"
                  id="companyDescription"
                  name="companyDescription"
                  placeholder="Your Message"
                  required
                ></textarea>
              </div>

              <div className="grid grid-cols-2 gap-4 mt-6">
                <div>
                  <button
                    className="bg-black text-white font-overpass py-2 px-10 w-full rounded-xl shadow-xl border-white hover:bg-white hover:text-primary hover:shadow-none"
                    type="submit"
                  >
                    Submit
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
