import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Nav } from "../components/nav";
import { Hero } from "../components/hero";
import { Intro } from "../components/intro";

import { CatelogueSnippet } from "../components/catelogue/catelogueSnippet";
import { Schemes } from "../components/schemes";
import { ContactForm } from "../components/contactForm";
import { Footer } from "../components/footer";
import { Testimonials } from "../components/testimonials";

export default function contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <h1 className="w-full text-center my-10 text-4xl uppercase -z-50">
        Contact us
      </h1>
      <div className="px-4 max-w-[1200px] mx-auto -z-50">
        <iframe
          src="https://snazzymaps.com/embed/375923"
          width="100%"
          height="440px"
        ></iframe>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 mt-8 mb-12 sm:mt-24 gap-8 px-4 max-w-[1200px] mx-auto">
        <div className="border-2 border-black flex flex-col justify-center gap-4 p-4">
          <img
            src="/loc.svg"
            className="fill-black w-[30px] h-[30px] mx-auto"
          />
          <h3 className=" w-full text-center text-3xl">Address</h3>
          <p className="w-full text-center text-xl">
            62 Station Rd, Croston, Preston PR26 9RN
          </p>
        </div>

        <div className="border-2 border-black flex flex-col justify-center gap-4 p-4">
          <img
            src="/contact.svg"
            className="fill-black w-[30px] h-[30px] mx-auto"
          />
          <h3 className=" w-full text-center text-3xl">Contact</h3>
          <p className="w-full text-center text-xl">
            07919282994, hello@justaesthetics.co.uk
          </p>
        </div>
      </div>

      <Testimonials />
      <ContactForm />
      <Footer />
    </div>
  );
}
