import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Nav } from "../components/nav";
import { Treatment } from "../components/treatmentTemplate/treatment";

export default function catalogue() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <div className="smmd:h-[400px] bg-gray-300 relative -z-20">
        <div className="absolute top-0 left-0 object-cover w-full smmd:h-[400px] h-full -z-10">
          <Image
            src="/lipbanner.png"
            alt="Banner Image"
            layout="fill"
            objectFit="cover"
            priority="true"
          />
        </div>

        <div className="pt-24 ">
          <h1 className="mt-4 text-left z-20 px-32 text-white text-3xl font-semibold">
            Aesthetic Treatments
          </h1>
          <p className="w-1/2 px-32 mt-4 text-left z-20 text-xl text-white">
            We specialise in wellbeing, aesthetic and skin treatments to bring
            value and happiness to our clients’ lives. For any questions left
            unanswered please refer to our <a>FAQ</a> or contact us via{" "}
            <a>our form</a>
          </p>
        </div>
      </div>

      <div className="mt-24 bg-lightGrey p-8 mx-24">
        <div className="grid grid-cols-1 gap-y-5 bg-white p-8">
          <h2 className=" text-2xl font-semibold text-center">
            Consulations For
          </h2>
          <p> Anti-Wrinkle treatment</p>
          <p> Skintox</p>
          <p>Eyelash Growth Serum</p>
          <p> Treatment From £100</p>
        </div>
        <div className="grid grid-cols-2 gap-y-5 bg-white p-8 mt-8">
          <h2 className="col-span-2 text-2xl font-semibold text-center">
            Golden Collagen Skin Fusion Treatment
          </h2>
          <p>1 Area</p>
          <p className="text-right">£200</p>
          <p>2 Areas</p>
          <p className="text-right">£300</p>
          <p>3 Areas</p>
          <p className="text-right">£400</p>
          <p>Revital-Eyes</p>
          <p className="text-right">£150</p>
        </div>
        <div className="grid grid-cols-3 gap-y-5 bg-white p-8 mt-8">
          <h2 className="col-span-3 text-2xl font-semibold text-center">
            Medical Grade Skin Care Treatments
          </h2>
          <p>Chemical Peel</p>
          <p className="text-center">X1 £50</p>
          <p className="text-right">X4 £160</p>
          <p>Luxury Chemical Peel</p>
          <p className="text-center">X1 £70</p>
          <p className="text-right">X4 £240</p>
          <p>Dermapeel</p>
          <p className="text-center">X1 £60</p>
          <p className="text-right">X4 £200</p>
          <p>Luxury Dermapeel</p>
          <p className="text-center">X1 £80</p>
          <p className="text-right">X4 £280</p>
          <p>Dermaplane</p>
          <p className="text-center">X1 £40</p>
          <p className="text-right">X4 £140</p>
          <p>The Ultimate dermaplane</p>
          <p className="text-center">X1 £50</p>
          <p className="text-right">X4 £180</p>
        </div>
        <div className="grid grid-cols-2 gap-y-5 bg-white p-8 mt-8">
          <h2 className="col-span-2 text-2xl font-semibold text-center">
            Dermal Fillers
          </h2>
          <p>Cheeks</p>
          <p className="text-right">FROM £150</p>
          <p>Nose To Mouth</p>
          <p className="text-right">FROM £150</p>
          <p>Mouth To Chin</p>
          <p className="text-right">FROM £150</p>
          <p>Peri-Oral Lines</p>
          <p className="text-right" w>
            FROM £150
          </p>
        </div>
        <div className="grid grid-cols-3 gap-y-5 bg-white p-8 mt-8">
          <h2 className="col-span-3 text-2xl font-semibold text-center">
            Medical Grade Skin Care Treatments
          </h2>
          <p>Juvederm Ultra</p>
          <p className="text-center">1/2ml £150</p>
          <p className="text-right">1ml £150</p>
          <p>Juvederm Vycross</p>
          <p className="text-center">1/2ml £150</p>
          <p className="text-right">1ml £150</p>
          <p className="col-span-3">
            Other Premium Brands Available Upon Request
          </p>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
